### ISSUE TITLE
java backend fails deploy on S3 bucket creation

### ISSUE THREAD

**Issue by jvargh** [aws-samples/serverless-webapp-mono-repo-ci-cd-java#165]
perhaps customize bucket name with a random value to prevent below

serverless-web-application-java-backend-bucket-demo already exists

**Comment by pankajagrawal16** [comment]
Hi @jvargh Thanks for opening the issue. I will look into fixing the static bucket names. If you already have a fix, PR is welcomed as well. :)

**Comment by pankajagrawal16** [comment]
This is fixed now.. Bucket and table names are randomly generated
