### ISSUE TITLE
PopulateCreateCollection	DELETE_FAILED	Custom Resource failed to stabilize in expected time

### ISSUE THREAD

**Issue by jvargh** [aws-samples/serverless-webapp-mono-repo-ci-cd-java#166]
Did remove all resources and yet unable to delete stack due to the PopulateCreateCollection which is labelled as below. How can this be removed so that stack can finally be deleted?

PopulateCreateCollection | serverless-web-application-java-backend-PopulateCreateCollection-O95385LWRHB6 | Custom::CreateCollection | DELETE_FAILED | Custom Resource failed to stabilize in expected time

**Comment by pankajagrawal16** [comment]
Hi @jvargh 

I will have a look at this, by any chance do you have logs from the custom resource lambda function?

**Comment by pankajagrawal16** [comment]
I have fixed a dependency issue, hopefully that should fix things for you @jvargh . Let me know if its still a problem.
